name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      - name: Create site directory
        run: mkdir -p ./site
      - name: Copy built files to site directory
        run: cp -a ./dist/. ./site/
        
      # Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        # env:
        #   PERSONAL_ACCESS_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
